[package]
name = "linear"
description = "cli tool for linear.app that uses git branch names and directory names to open issues and team pages"
version = "0.0.6"
license = "MIT"
repository = "https://github.com/schpet/linear-cli"
binaries = ["linear"]
build-command = ["deno compile main.ts"]
