// User-approved native clap diagnostics and strict numeric input surfaces.
// This closed catalog is independently SHA-pinned in native-parser-goldens.sha256.
export const NATIVE_PARSER_CONTRACTS = new Map<string, [string, string[]]>([
  ["c002-json-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c009-json-rejected", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c009-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c010-bad-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c015-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c016-collision-bare", ["CLAP-NATIVE-PARSER", ["exit", "stderr"]]],
  ["c016-collision-raw-key", ["CLAP-NATIVE-PARSER", ["exit", "stderr"]]],
  ["c016-collision-true-workspace", ["CLAP-NATIVE-PARSER", ["exit", "stderr"]]],
  ["c016-explicit-empty-team", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c016-root-local-duplicate", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c016-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c016-whitespace-team-workspace", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stderr",
  ]]],
  ["c019-bad-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c019-empty-team", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c019-missing-option-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c020-empty-team", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c020-missing-team-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c020-negative-offset", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c020-offset-minus-zero", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c020-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c021-team-empty", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c021-type-case", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c021-type-invalid", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c022-bad-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c022-url-bad-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c022-workspace-missing-value", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c023-empty-status", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c023-empty-team", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c023f-missing-team", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c023f-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c024-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c027-json-equals-empty", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c027-repeated-j", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c027-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c030-duplicate-project", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c030-project-empty-arg", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c030-project-equals-empty-last", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c030-project-no-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c030-repeated-j", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c030-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-duplicate-project", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-project-empty-arg", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-project-equals-empty", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-project-no-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-repeated-j", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c031-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c032-empty-description-value", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c033-empty-name", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c033-sort-infinity", ["C033-FINITE-DECIMAL-INPUT", ["stdout", "stderr"]]],
  ["c033-sort-radix", ["C033-FINITE-DECIMAL-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c033n-initiative-fraction", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stderr",
  ]]],
  ["c033n-initiative-padded-nbsp", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stderr",
  ]]],
  ["c033n-initiative-zero", ["RUST-POSITIVE-LIMIT-INPUT", ["exit", "stderr"]]],
  ["c033n-project-padded", ["RUST-POSITIVE-LIMIT-INPUT", ["exit", "stderr"]]],
  ["c035-json-equals-empty", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c035-limit-empty-value", ["RUST-POSITIVE-LIMIT-INPUT", [
    "stdout",
    "stderr",
  ]]],
  ["c035-limit-equals-missing", ["RUST-POSITIVE-LIMIT-INPUT", [
    "stdout",
    "stderr",
  ]]],
  ["c035-limit-equals-takes-id", ["RUST-POSITIVE-LIMIT-INPUT", [
    "stdout",
    "stderr",
  ]]],
  ["c035-limit-exponent", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c035-limit-hex", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c035-limit-missing", ["RUST-POSITIVE-LIMIT-INPUT", ["stdout", "stderr"]]],
  ["c035-limit-negative", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c035-limit-next-flag", ["RUST-POSITIVE-LIMIT-INPUT", ["stdout", "stderr"]]],
  ["c035-limit-nonnumeric", ["RUST-POSITIVE-LIMIT-INPUT", [
    "stdout",
    "stderr",
  ]]],
  ["c035-limit-repeat", ["RUST-POSITIVE-LIMIT-INPUT", ["stdout", "stderr"]]],
  ["c035-limit-zero", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c035-repeated-json", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c035-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-empty-status", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-missing-owner-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-missing-status-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-owner-empty", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-owner-next-flag", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c037-repeated-json", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c037-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c038-repeated-json", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c038-unknown-flag", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c039-duplicate-name", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c039-empty-description-value", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c039-empty-name", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c039-name-missing-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c039-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c048-limit-hex", ["RUST-POSITIVE-LIMIT-INPUT", [
    "exit",
    "stdout",
    "stderr",
    "graphql-fixture",
    "graphql-user-agent",
  ]]],
  ["c048-limit-nonnumeric", ["RUST-POSITIVE-LIMIT-INPUT", [
    "stdout",
    "stderr",
  ]]],
  ["c085-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c085-workspace-missing", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c086-complete-workspace-rejected", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c086-name-empty", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c086-name-missing", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c086-name-repeated", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c086-shell-workspace-rejected", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c2-bulk-empty-tail", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c2-bulk-unknown-option", ["CLAP-NATIVE-PARSER", ["exit", "stderr"]]],
  ["c2-empty-help-suffix", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stdout",
    "stderr",
  ]]],
  ["c2-empty-switch-suffix", ["CLAP-NATIVE-PARSER", ["exit", "stderr"]]],
  ["c2-issue-short-version", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c2-issue-workspace-missing", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c2-mine-hidden-option-typo", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c2-mine-sort-help-value", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["c2-root-negated-workspace-help", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["c2-workspace-delimiter-value", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stdout",
    "stderr",
  ]]],
  ["c2-workspace-missing-help", ["CLAP-NATIVE-PARSER", [
    "exit",
    "stdout",
    "stderr",
  ]]],
  ["grammar-issue-unknown-option", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["grammar-issue-version", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["grammar-root-workspace-missing", ["CLAP-NATIVE-PARSER", [
    "stdout",
    "stderr",
  ]]],
  ["parser-invalid-variable", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
  ["parser-unknown-option", ["CLAP-NATIVE-PARSER", ["stdout", "stderr"]]],
])

export function nativeParserContract(
  id: string,
): [string, string[]] | undefined {
  return NATIVE_PARSER_CONTRACTS.get(id)
}
