pub mod auth_list;
pub mod auth_whoami;
pub mod client;
pub mod comments;
pub mod completions;
pub mod cycle_list;
pub mod cycle_view;
pub mod display;
pub mod document_comment_list;
pub mod initiative_comment_list;
pub mod initiative_create;
pub mod initiative_list;
pub mod initiative_update_list;
pub mod initiative_view;
pub mod issue_comment_delete;
pub mod label_list;
pub mod milestone_create;
pub mod milestone_delete;
pub mod milestone_list;
pub mod milestone_update;
pub mod milestone_view;
pub mod project_comment_list;
pub mod project_delete;
pub mod project_list;
pub mod project_update_list;
pub mod project_view;
pub mod prosemirror;
pub mod relative_time;
pub mod table;
pub mod team_create;
pub mod team_id;
pub(crate) mod team_key;
pub mod team_list;
pub mod team_members;
pub mod team_states;
pub mod template_data;
pub mod template_json;
pub mod template_list;
pub mod template_view;
pub mod user_list;

mod style;

pub mod issue_details;

pub mod label_create;
